# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: trusty
language: r
sudo: required

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx
  
osx_image: xcode9.4

env:
 global:
   - CRAN: http://cran.rstudio.com

addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin
      - libgdal1-dev
      - libproj-dev