# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

jobs:
  include:
    - os: linux
      dist: trusty
      r: 
        - devel
        - release
      before_install:
        - chmod +x configure
        - chmod +x cleanup
      addons:
        apt:
          packages:
          - libudunits2-dev
          - gdal-bin
          - libgdal1-dev
          - libproj-dev
    - os: osx
      osx_image: xcode9.4
      r: release
      before_install:
        - chmod +x configure
        - chmod +x cleanup
      brew_packages:
          - udunits
r_packages:
  - knitr
  - rmarkdown
  - ggplot2
  - ggvoronoi
  - sampling
  - BalancedSampling
  - sp
  - sf