# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
dist: trusty
sudo: required

r:
  - release
  - devel

before_install:
  - chmod +x configure
  - chmod +x cleanup

os:
  - linux
  - osx
  
osx_image: xcode9.4

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
  - knitr
  - rmarkdown
  - ggplot2
  - ggvoronoi
  - kableExtra
  - magrittr
  - sampling
  - BalancedSampling
  - sp
  - sf
  - stats
  
addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin
      - libgdal1-dev
      - libproj-dev