# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
dist: trusty
sudo: required

matrix:
  include:
  - r: devel
    before_install:
      - chmod +x configure
      - chmod +x cleanup
    addons:
      apt:
        packages:
        - libudunits2-dev
        - gdal-bin
        - libgdal1-dev
        - libproj-dev
  - r: release
    before_install:
      - chmod +x configure
      - chmod +x cleanup
    addons:
      apt:
        packages:
        - libudunits2-dev
        - gdal-bin
        - libgdal1-dev
        - libproj-dev
  - r: release
    os: osx
    osx_image: xcode9.4
    before_install:
      - chmod +x configure
      - chmod +x cleanup
    homebrew:
      packages:
        - udunits

r_packages:
  - knitr
  - rmarkdown
  - ggplot2
  - ggvoronoi
  - sampling
  - BalancedSampling
  - sp
  - sf