# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

r:
  - release

os:
  - linux
  - osx

dist: trusty
osx_image: xcode9.4
  
before_install:
  - chmod +x configure
  - chmod +x cleanup  

addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin
      - libgdal1-dev
      - libproj-dev

brew_packages:
  - udunits
  
r_packages:
  - knitr
  - rmarkdown
  - ggplot2
  - ggvoronoi
  - sampling
  - BalancedSampling
  - sp
  - sf
  